/* Builds the landing page gradient out of the colours of the real builds.
 *
 * The source of truth is the AMBIENT map in public/script.js, which already
 * pairs every build with the two colours that define it. That map is what
 * tints the page as you scroll past each build, so deriving the hero
 * gradient from the same numbers means the landing page and the rest of the
 * site can never drift apart, and there is only one place to edit a colour.
 *
 * (Sampling the images directly was tried first and was worse: dark
 * saturated pixels dominate, and the Enchanted Grove came out a muddy red
 * when what makes it the grove is emerald and magenta. The curated colours
 * describe the builds better than their own average pixels do.)
 *
 * Writes:
 *   public/palette.css   custom properties for the CSS gradient
 *   src/palette.json     the same colours for the WebGL hero layer
 *
 * Run with: node scripts/build-palette.mjs
 */
import fs from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.join(import.meta.dirname, '..')

// The builds the landing page leads with, in the order they appear.
const FEATURED = [
  ['img/stud-hub', 'Stud Trading Hub'],
  ['img/stud-tycoon', 'Stud Tycoon Islands'],
  ['img/enchanted', 'Enchanted Grove'],
  ['img/wizard-tower', 'Wizard Tower'],
  ['img/astral-lounge', 'Astral Lounge'],
  ['img/astral-promenade', 'Astral Promenade'],
]

/* ------------------------------------------------- read AMBIENT from source */

const js = await fs.readFile(path.join(ROOT, 'public/script.js'), 'utf8')
const block = js.slice(js.indexOf('const AMBIENT'), js.indexOf('};', js.indexOf('const AMBIENT')))

const ambient = {}
for (const m of block.matchAll(/"([^"]+)":\s*\[\s*"(#[0-9a-fA-F]{6})",\s*"(#[0-9a-fA-F]{6})"/g)) {
  ambient[m[1]] = [m[2], m[3]]
}
for (const [folder] of FEATURED) {
  if (!ambient[folder]) throw new Error('AMBIENT is missing ' + folder)
}

/* ---------------------------------------------------------- colour helpers */

const toRgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16))
const toHex = (rgb) => '#' + rgb.map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('')

function rgbToHsl([r, g, b]) {
  r /= 255; g /= 255; b /= 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b)
  const l = (max + min) / 2
  if (max === min) return [0, 0, l]
  const d = max - min
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
  let h
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6
  else if (max === g) h = ((b - r) / d + 2) / 6
  else h = ((r - g) / d + 4) / 6
  return [h, s, l]
}

function hslToRgb([h, s, l]) {
  if (s === 0) { const v = l * 255; return [v, v, v] }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s
  const p = 2 * l - q
  const f = (t) => {
    if (t < 0) t += 1
    if (t > 1) t -= 1
    if (t < 1 / 6) return p + (q - p) * 6 * t
    if (t < 1 / 2) return q
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6
    return p
  }
  return [f(h + 1 / 3), f(h), f(h - 1 / 3)].map((v) => v * 255)
}

/* Relative luminance and contrast, so the gradient can be checked rather
   than assumed to be dark enough for white type. */
function relLum(rgb) {
  const f = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4) }
  return 0.2126 * f(rgb[0]) + 0.7152 * f(rgb[1]) + 0.0722 * f(rgb[2])
}
const contrast = (a, b) => {
  const [l1, l2] = [relLum(a), relLum(b)]
  return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05)
}

/* ------------------------------------------------------------------ build */

// The lead colour of each build, kept saturated but pulled to a lightness
// that can sit behind white type without fighting it.
const stops = FEATURED.map(([folder, name]) => {
  const [h, s] = rgbToHsl(toRgb(ambient[folder][0]))
  const glow = toHex(hslToRgb([h, Math.min(0.95, s * 1.05), 0.52]))
  const deep = toHex(hslToRgb([h, Math.min(0.95, s * 1.1), 0.12]))
  return { name, folder, glow, deep }
})

const WHITE = [255, 255, 255]
const report = stops.map((s) => ({
  build: s.name,
  deep: s.deep,
  contrastOfWhiteOnDeep: +contrast(WHITE, toRgb(s.deep)).toFixed(2),
}))

const css = `/* Generated by scripts/build-palette.mjs. Do not edit by hand.
 *
 * Every colour here is the lead colour of one real build on this site,
 * taken from the same AMBIENT map that tints the page as you scroll past
 * that build. Change a colour there, re-run the script, and the landing
 * page follows.
 *
 * --bp-N       the build's colour at full strength, for the glow
 * --bp-N-deep  the same hue at 12% lightness, for the bed it sits on
 */
:root{
${stops.map((s, i) => `  --bp-${i + 1}:${s.glow};       /* ${s.name} */`).join('\n')}

${stops.map((s, i) => `  --bp-${i + 1}-deep:${s.deep};  /* ${s.name} */`).join('\n')}
}
`

await fs.writeFile(path.join(ROOT, 'public/palette.css'), css)
await fs.writeFile(
  path.join(ROOT, 'src/palette.json'),
  JSON.stringify({ stops: stops.map(({ name, glow, deep }) => ({ build: name, glow, deep })) }, null, 2) + '\n'
)

console.log('landing page palette, one colour per featured build:\n')
for (const s of stops) console.log('  ' + s.glow + '  ' + s.deep + '   ' + s.name)
console.log('\nwhite text on each deep tone:')
for (const r of report) {
  console.log('  ' + String(r.contrastOfWhiteOnDeep).padStart(6) + ':1  ' + r.build + (r.contrastOfWhiteOnDeep < 7 ? '   <-- thin' : ''))
}
console.log('\nwrote public/palette.css and src/palette.json')
